config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :factories do
     resources :bookings, only: [:show, :create, :update]
  end
  resource :dashboard, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :factory
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :factory
  belongs_to :user


  # I can do @booking.accepted!, @booking.declined!, etc.
  enum status: [ :pending, :accepted, :declined ]
  before_create :set_total_price

  def set_total_price
    self.total_price = (self.end_date - self.start_date).to_i * self.factory.price_per_day
  end
end

app/models/factory.rb
class Factory < ApplicationRecord
  belongs_to :user
  has_many :bookings
  geocoded_by :location

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

  after_validation :geocode, if: :will_save_change_to_location?

  # pg_search_scope :global_search,
  #   against: [ :name, :description ],
  #   associated_against: {
  #     user: [ :first_name, :last_name ]
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :factories, dependent: :destroy
  has_many :locations
  has_many :recieved_bookings, through: :factories, source: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private


  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @factory = Factory.find(params[:factory_id])
    @booking.user = current_user

    @booking.factory = @factory
    authorize @booking
    if @booking.save
      redirect_to factory_booking_path(@factory, @booking)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(status: params[:status])
      redirect_to dashboard_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @recieved_bookings = current_user.recieved_bookings
    @bookings = current_user.bookings
    @factories = current_user.factories
  end
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  def index
    @factories = policy_scope(Factory).order(created_at: :desc)
    authorize @factories
    @markers = @factories.geocoded.map do |factory|
      {
        lat: factory.latitude,
        lng: factory.longitude
      }
    end
  end

  def show
    @factory = Factory.find(params[:id])
    @booking = Booking.new
    authorize @factory
  end

  def new
    @factory = Factory.new
    authorize @factory
  end

  def create
    @factory = Factory.new(factory_params)
    @factory.user = current_user
    if @factory.save
      redirect_to factory_path(@factory)
    else
      render :new
    end
    authorize @factory
  end

  def destroy
    @factory = Factory.find(params[:id])
    if @factory.destroy
      redirect_to factories_path
    end
    authorize @factory
  end

  private

  def factory_params
    params.require(:factory).permit(:name, :description, :location, :price_per_day, :capacity, :user_id, :body, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_beer-card.html.erb
<div class="beer-list">
  <div class="d-flex">

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2021/11/ALAFU_cascabelle-prairies_473ml_3d.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>Cascabelle des prairies</h3>
          <p><em>Double IPA à l'avoine</em></p>
          <p>8,2% alc./vol.</p>
        </div>
      </div>

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2021/09/ALAFU_Coyloup_3D.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>Coyloup</h3>
          <p><em>Brett IPA - Citra</em></p>
          <p>7,5% alc./vol.</p>
        </div>
      </div>

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2021/06/ALAFU_Frankie_3D.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>Frankie</h3>
          <p><em>IPA Saline</em></p>
          <p>7,5% alc./vol.</p>
        </div>
      </div>

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2021/06/ALAFU_Generique_3D.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>IPA du Far Est</h3>
          <p><em>Ananas</em></p>
          <p>7,5% alc./vol.</p>
        </div>
      </div>

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2021/05/ColibriRufus_3D.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>Colibris Rufus</h3>
          <p><em>Nano IPA</em></p>
          <p>2% alc./vol.</p>
        </div>
      </div>

      <div class="beer-card">
        <img src="https://www.alafut.qc.ca/app/uploads/2018/08/ALAFU_PtiteCocotte_3D.png" alt="">
        <div class="beer-descitpion-layout">
          <h3>P'tite Cocotte</h3>
          <p><em>Session IPA</em></p>
          <p>3,8% alc./vol.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/beers/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Beers</title>
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">
  </head>
  <body>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.gea.com/fr/binaries/gea-craft-brewing-plug-and-win_tcm29-50426.jpg)">
  Discover our Craft Beers
</div>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2021/11/ALAFU_cascabelle-prairies_473ml_3d.png)">
    Cascabelle des prairies
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2021/09/ALAFU_Coyloup_3D.png)">
    Coyloup
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2021/06/ALAFU_Frankie_3D.png)">
    Frankie
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2021/06/ALAFU_Generique_3D.png)">
    IPA du Far Est Ananas
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2021/05/ColibriRufus_3D.png)">
    Colibris Rufus
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.alafut.qc.ca/app/uploads/2018/08/ALAFU_PtiteCocotte_3D.png)">
    P'tite Cocotte
  </div>
</div>
</body>
</html>

app/views/dashboards/show.html.erb
<h1>Welcome to your dashboard</h1>
<div class="container-dashboard">
<h2>Your bookings</h2>
<div class="card-grid">
<% @bookings.each do |booking| %>
<div class="booking-card">
<h5><%= booking.name %></h5>
<p>Start Date: <%= booking.start_date %></p>
<p>End Date: <%= booking.end_date %></p>
<p>Total days: <%= (booking.end_date - booking.start_date).to_i %></p>
<p>Total price: $<%= booking.agreed_price %></p>
<p>Booking status: <%= booking.status %></p>
</div>
<% end %>
</div>
<h2>Your requests</h2>
<div class="card-grid">
<% @bookings.each do |booking| %>
<% if booking.pending? %>
<div class="booking-card">
<h5><%= booking.user.email %></h5>
<p>Start Date: <%= booking.start_date %></p>
<p>End Date: <%= booking.end_date %></p>
<p>Total days: <%= (booking.end_date - booking.start_date).to_i %></p>
<p>Total price: $<%= booking.agreed_price %></p>
<p>booking status: <%= booking.status %></p>
<%= link_to "Accept", booking_path(booking,{status: "accepted"}), method: :patch, class: "btn-accept"  %>
</div>
<% end %>
<% end %>
</div>
</div>

app/views/factories/_form.html.erb
<%= simple_form_for(factory) do |f| %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/factories/avatar.html.erb
<img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
<img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
<img class="avatar-square" alt="avatar-square" src="https://kitt.lewagon.com/placeholder/users/krokrob" />

app/views/factories/index.html.erb
<head>

<link href='mapbox://styles/evanlaulom/ckw652owj21ej15p1qhu14oni' rel='stylesheet' />

</head>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.gea.com/fr/binaries/gea-craft-brewing-plug-and-win_tcm29-50426.jpg)">
  Discover our Craft Beer Factories
</div>
<div class="factory-position">
  <div class="left">
    <div class="cards">
      <% @factories.each do |factory| %>
        <%= link_to factory_path(factory) do %>
        <%= render 'shared/card-category', factory: factory %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="right">
    <div id="map"
     style="width: 100%; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
</div>

app/views/factories/new.html.erb
<div class= background-new-factory style="background-image: url('https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHdvb2QlMjB0ZXh0dXJlfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80')">
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a new factory 🍻</h3>
        <%= simple_form_for (@factory) do |f| %>
          <%= f.input :name, placeholder: 'Enter the name of your factory' %>
          <%= f.input :location, placeholder: 'Where is located your factory?' %>
          <%= f.input :description, prompt: 'Tell us more about your Craft beer factory', input_html: { class: 'select2' } %>
          <%= f.input :price_per_day, placeholder: 'What is the price per person?' %>
          <%= f.input :capacity, placeholder: 'What is the maximum capacity?' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/factories/show.html.erb
<div class="factory-show-layout">
  <div class="previous-button">
    <%= link_to '←', factories_path %>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'shared/carrousel' %>
    </div>
  </div>
  <br>

  <h2 class="text-glow" style="font-size: 60px; text-align: center"><%= @factory.name %></h2>
  <div class="factory-description">
    <div class="left">
      <div class="col">
        <h2 style="padding-bottom: 50px">Exceptional beers aged in oak barrels</h2>
        <p>À la Fût is always striving to offer high quality brews and to keep on innovating. We have been amongst the first microbreweries in Québec to use cans, to brew beer aged in oak barrels, to develop sour beers with Brettanomyces yeast, to offer beer aged in oak barrels in cans, and to create collaborative brews with other microbreweries in Québec, Ontario and soon the United States.À la Fût stands out on the Québec brewing landscape with its specialty beers. As such, we have won over 30 distinctive awards since 2010 in London, the United States and Canada. The Rouge de Mékinac alone has won 13 awards including the “2012 Beer of the Year in Canada” and the world’s best Kriek-style beer in 2014 and 2015. Our 400 barrel cellar is now one of the largest in Québec. The brewery will soon house a tasting room; but in the meantime, it offers guided tours of the brewery during the summer as part of the Western Kapibouska Village, or overbooking for groups.</p>
        <p><%= @factory.location %></p>
      </div>
    </div>
    <div class="right">
      <div class="booking-layout">
        <div class="col" style="width: 400px; margin: 0 auto;">
          <div class="price-guest-layout">
            <div class="price-guest">
              <h2 style="text-align: left; color: #B48F02; padding-left: 20px; font-size: 60px"><%= @factory.price_per_day %> €</h2>
              <h2><%= @factory.capacity %> guests</h2>
            </div>
            <div class="number-guest">
              <label for="numberGuest">Number of guests</label>
              <input id="numberGuest" type="number" name="numberGuest" value="1">
            </div>
            <%= render 'shared/calendar-form' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <h2 class="text-glow ml-5">Which kind of beer do we offer ?</h2>
  <br>

  <%= render 'beers/beer-card' %>

  <br>
  <h2 style="padding-left: 25px">Where can you find us?</h2>
  <br>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://miro.medium.com/max/1200/1*qYUvh-EtES8dtgKiBRiLsA.png)">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAppCraftBeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'https://clipart.world/wp-content/uploads/2020/08/beer-mug-logo-design-png-transparent.png' %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/checkout.html.erb
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">

            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Continue to checkout" class="btn">
      </form>
    </div>
  </div>

  <div class="col-25">
    <div class="container">
      <h4>Cart
        <span class="price" style="color:black">
          <i class="fa fa-shopping-cart"></i>
          <b>4</b>
        </span>
      </h4>
      <p><a href="#">Product 1</a> <span class="price">$15</span></p>
      <p><a href="#">Product 2</a> <span class="price">$5</span></p>
      <p><a href="#">Product 3</a> <span class="price">$8</span></p>
      <p><a href="#">Product 4</a> <span class="price">$2</span></p>
      <hr>
      <p>Total <span class="price" style="color:black"><b>$30</b></span></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

  <head>

  </head>

  <body class="body-home">
    <div class="banner">
    <div class="company_name">
      <h1>Beer Origins</h1>
      <p>Discover all new Craft Beer factories around you</p>
        <div class="search-space">
          <%= form_tag factories_path, method: :get do %>
            <input id="input" type="search" autocomplete="on" spellcheck="false" role="combobox" aria-live="polite" placeholder="I'm searching for..." style="padding:10px 20px">
          <% end %>
        </div>
      </div>
    </div>
<div class="space">⬇</div>

    <h4>TOP FACTORIES</h4>

    <% image_urls = ["https://images.the500hiddensecrets.com/2019-04/ghent-drink-my_generator_broke_down.jpg?auto=format&fit=max&h=1080&ixlib=php-1.1.0&q=65&w=1920&s=1ca514bc52daafbf0b7c4c13cd905c22", "https://www.filepicker.io/api/file/2vvCccMTQeO3EUeQsIBa/convert?&w=1540&h=748&fit=crop", "https://uolala.s3.amazonaws.com/event-pictures/b-visita-a-la-antigua-fabrica-de-estrella-damm-81433-450bca.jpg", "https://www.tastytales.tv/uploads/resized/13/pics_breweries_seef_web4.jpeg",
    "https://media-cdn.tripadvisor.com/media/photo-s/0c/53/6c/a6/nuestro-bar-our-taproom.jpg", "https://pbs.twimg.com/media/C-6keTQXsAABfth.jpg", "https://www.thehopleaves.com/uploads/7/3/3/6/73368263/naparbcn-entry-1-of-1_orig.jpg", "https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2017/08/11/9aeab86ad1d440b4ac6c3e1243ab095e_sawmill-oct16-2109.jpg"] %>

    <% text = ['Dok Brewing, 23€/p.', 'Brouwerij Noordt, 15€/p.', 'Fàbrica Estrella Damm, 30€/p.', 'Brouwerijcafé, 21€/p.', 'Garage Beer, 28€/p.', 'Abirradero, 35€/p.', 'NaparBCN, 42€/p.', 'Brouwerij Marieke, 39€/p.'] %>

    <% descriptions = ["Dok-Noord 4B, 9000 Gent, Belgium", 'Zaagmolenkade 46, 3035 KA Rotterdam, Netherlands', "Carrer del Rosselló, 515, 08025 Barcelona", ' Indiestraat 21, 2000 Antwerpen, Belgium', 'Carrer del Consell de Cent, 261, 08011 Barcelona, Spain', 'Carrer de Vila i Vilà, 77, 08004 Barcelona', 'Carrer de la Diputació, 451, 08013 Barcelona', 'Amsterdam, Noord-Holland, Netherlands'] %>

    <%= link_to factories_path do %>

    <div class="factories_home">
    <%= render 'shared/card', url: image_urls[0], description: text[0], inside: descriptions[0] %>
    <%= render 'shared/card', url: image_urls[1], description: text[1], inside: descriptions[1] %>
    <%= render 'shared/card', url: image_urls[2], description: text[2], inside: descriptions[2] %>
    <%= render 'shared/card', url: image_urls[3], description: text[3], inside: descriptions[3] %>
    </div>

    <div class="second_factories_home">
    <%= render 'shared/card', url: image_urls[4], description: text[4], inside: descriptions[4] %>
    <%= render 'shared/card', url: image_urls[5], description: text[5], inside: descriptions[5] %>
    <%= render 'shared/card', url: image_urls[6], description: text[6], inside: descriptions[6] %>
    <%= render 'shared/card', url: image_urls[7], description: text[7], inside: descriptions[7] %>
    </div>
    <% end %>
  </body>

</html>

app/views/shared/_calendar-form.html.erb
<div class="container-form">
  <div class="form-wrapper" style="width: 300px; margin: 0 auto; text-align: left">

    <%= simple_form_for [@factory, @booking]  do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: { id: "range_start" } %>
      <%= f.input :end_date, as: :string, required: false, input_html: { id: "range_end" } %>
      <%= f.button :submit, "Reserve", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="color:black" text="align">
        Your reservation now confirmed !
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card">
  <div class="image" style="background: url(<%= url %>);background-size: cover">
  <span class="text_inside"><%= inside %></span>
  </div>
  <div class="text_outside" ><%= description %></div>
</div>

app/views/shared/_cards.html.erb
<div class="cards"></div>

app/views/shared/_navbar.html.erb
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;400&display=swap" rel="stylesheet">
  </head>

  <body>
  </body>
</html>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://clipart.world/wp-content/uploads/2020/08/beer-mug-logo-design-png-transparent.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="navbar-text">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Factories", factories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://www.clipartmax.com/png/middle/424-4242023_fa-user-circle-icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if policy(Factory).create? %>
            <%= link_to "New Factory", new_factory_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>